### ISSUE TITLE
Casting option broken

### ISSUE THREAD

**Issue by milkyskies** [Sentropic/SkillAPI-s#15]
**Describe the bug**
Enabling the main casting feature does not seem to work, or does not work completely on my 1.16.4 Paper server.
I've cleared the plugin folder several times to retry with varying results. It worked as written in the config only one time. The other times, either left/right clicking with the skill book does nothing OR moves the cursor to the left-most position without displaying any skills (both of these also seem to duplicate the skill book). Attempting to press Q while holding it either drops the book and gives another, or it opens up the skill bar editor without displaying any skills.

**To Reproduce**
Enable main casting in the config with bars also enabled, and reload the plugin with /class reload or restart the server.

**Version**
SkillAPI v1.97
Paper 409 (1.16.4-R0.1-SNAPSHOT)

**Comment by Sentropic** [comment]
Are you getting any warns or errors printed in the console?

**Comment by milkyskies** [comment]
No errors.

**Comment by Sentropic** [comment]
So, I tried to look into this and the code is a real mess, and couldn't figure it out. I'm tagging this as low priority, so maybe I'll look into it in the future. If someone else is willing to help with they're welcome to make a pull request. Sorry about the inconvinience.
