### ISSUE TITLE
some little suggestions

### ISSUE THREAD

**Issue by HOWTOCHICKEN** [Sentropic/SkillAPI-s#17]
hello coder, gave you two suggestions.

**Is your feature request related to a problem? Please describe:**
to comfortably, I set the combo to cast skill, and I made an archer to my RPG server, but when I shoot an arrow the R will trigger. 

**Describe the solution you'd like:**
can you add the set is "if-click: L": your compo begin when L is click.
(hope add to the class file)
(like "wynncraft")

-

**Is your feature request related to a problem? Please describe:**
in a test. I have found a level 5 archer hold and a level limit of 35 bows to cast the damage skill, and the skill will add damage from the lore. 

**Describe the solution you'd like:**
can you adjust the limit when you hold the item not pass the item restrictions but you still cast the skill? or switch her main hand and cancel the skill. 
("drop-weapon" so dirty :frowning: )

-

my English very sucks, but I hope my suggestion will more perfect the plugins.

**Comment by Sentropic** [comment]
Let's see if I understood. For the first suggestion, you want combos to start with L only?
And in the second: The item with lore stats is an skill item?

**Comment by HOWTOCHICKEN** [comment]
"you want combos to start with L only?"
add "if-click:" in "SkillAPI\dynamic\class\"
if the class is warrior whose main weapon is an axe, I will set the "if-click: R" in "SkillAPI\dynamic\class\warrior.yml" because he always uses L button to normal attack.
if the class is mage whose main weapon is a wand, I will set the "if-click: L" in "SkillAPI\dynamic\class\mage.yml" because he always uses L button to normal attack.

add this setting will control the combo when to use it. like "wynncraft", if the warrior click R, means he wants to cast skills. now detect the second and third button to decide the warrior want to cast which skill.

"The item with lore stats is an skill item?"
if I set "damage lore" is "fire damage:{value}" in the skill, I can hold a high-level fire weapon to add the skill damage. but I can't use this weapon because my class level not arrive. but I still can take It to skill damage.

thank you for your patience!

**Comment by Sentropic** [comment]
About the first issue, you can simply configure your combos so that all start with the key you want.

About the second: The current functionality is so that an item that doesn't meet the required level won't add its attributes to the player, which is what I understand you want.

**Comment by HOWTOCHICKEN** [comment]
you got it.

**Comment by Sentropic** [comment]
Ok then.
