### ISSUE TITLE
about bow and lore requirements

### ISSUE THREAD

**Issue by HOWTOCHICKEN** [Sentropic/SkillAPI-s#18]
please fix the bug is bow, crossbow, trident, shield, and all use R button tool.

**To Reproduce:**
I can use the level limit 20 bow but my class level is 1.

**Expected behavior:**
my bow can shoot but I set "lore-class-text" and "lore-level-text" in config file.
should my can't use the bow.

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Minecraft Version: spigot 1.16.5
Skillapi Version: use newest version(1.97) 

**show:**
https://www.youtube.com/watch?v=bfUcFtUUaEo

my English very sucks, but I hope my suggestion will more perfect the plugins.

**Comment by Sentropic** [comment]
What did you put in the 'lore-level-text' field in the config?

**Comment by HOWTOCHICKEN** [comment]
this one
lore-level-text: 'Requires level:'

and I find a focus. I can't use the bow in the video for normal attack. will display "you cannot equip that item".
