### ISSUE TITLE
Dynamic Editor: Not using 1.12 IDs

### ISSUE THREAD

**Issue by Lovyxia** [Sentropic/SkillAPI-s#24]
Note: Aside from English, I also speak Spanish, and can understand Portuguese and French, so you can post the issue in the language you prefer among those.

**Describe the bug**
When I wanted to apply "Mob Spell" particles, there were only newer names for them such as "Spell Mob", same goes for example for "Red Dust" (1.12) which is instead "Redstone" (newer).

This might also apply for other mechanics that involve IDs that changed since 1.13 or later.

**To Reproduce**
1. Set the Dynamic Editor to 1.12
2. Open particle selection on a "Particle" mechanic.

**Expected behavior**
1.12 compatible values should be shown.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Mozilla Firefox
 - Version 85.0

**Comment by Lovyxia** [comment]
![grafik](https://user-images.githubusercontent.com/37264533/106656151-9559ee80-659a-11eb-9628-475c11f6c896.png)
![grafik](https://user-images.githubusercontent.com/37264533/106656253-bc182500-659a-11eb-8f66-adf8d4481714.png)

Here are screenshots for comparison between the editor for original SkillAPI (2nd picture) and SkillAPI-s (1st picture), showing the difference in particle IDs.

**Comment by Lovyxia** [comment]
Update: This is no longer of importance to me personally. SkillAPI-s seems to have a number of other issues with 1.12 however.

**Comment by Sentropic** [comment]
This is intentional, as alot of the old names were very arbitrary. I changed it so that it always uses the Bukkit values to avoid confusions using obsolete names. All the previously supported particle names are still there.
