### ISSUE TITLE
custom_model_data Not working

### ISSUE THREAD

**Issue by Niinnee** [Sentropic/SkillAPI-s#33]
custom_model_data Not working

**Comment by Sentropic** [comment]
Did you enable custom model data in the config?

**Comment by Niinnee** [comment]
> Did you enable custom model data in the config?

                            Armor Stand-s: 
                              type: 'mechanic'
                              indicator: '3D'
                              data: 
                                icon-key: 'chixushijian'
                                counts: 'True'
                                key: ''
                                duration-base: '20'
                                duration-scale: '5'
                                name: '&2&l治疗图腾'
                                name-visible: 'False'
                                follow: 'False'
                                gravity: 'True'
                                tiny: 'False'
                                arms: 'True'
                                base: 'False'
                                visible: 'false'
                                marker: 'True'
                                forward-base: '1'
                                forward-scale: '0'
                                upward-base: '0'
                                upward-scale: '0'
                                right-base: '0'
                                right-scale: '0'
                                indicator: '2D'
                              children: 
                                Armor-t: 
                                  type: 'mechanic'
                                  indicator: '3D'
                                  data: 
                                    icon-key: ''
                                    counts: 'True'
                                    slot: 'Head'
                                    material: 'Diamond hoe'
                                    amount: '1'
                                    durability: '0'
                                    data: '9'
                                    custom: 'True'
                                    name: 'Name'
                                    lore: 
                                    - '治疗图腾'
                                    overwrite: 'True'
                                    indicator: '2D'
                                  children:  {}

this custom_model_data Not working ，enable custom model data in the config。Confirm that there is no problem with the resource
