### ISSUE TITLE
question: wich github repo is a primary repo for skill api updated main branch

### ISSUE THREAD

**Issue by poohzaza166** [Sentropic/SkillAPI-s#40]
is this a correct repo https://www.spigotmc.org/resources/skillapi-continued-custom-classes-skills-and-more-works-on-1-16-5-proskillapi.91913/

since everyone is trying to fork it

**Comment by mkcoldwolf** [comment]
There is only like 1 fork, where u see "everyone" from?
Also, if they really want to continue the work, there is no point of clone and reupload instead of forking this, or the original one
