### ISSUE TITLE
Particle Projectile sometimes hits more than one entity even without pierce

### ISSUE THREAD

**Issue by yhdev7935** [Sentropic/SkillAPI-s#5]
Describe the bug
Particle Projectile Damage bug

To Reproduce
1. [Video](https://cdn.discordapp.com/attachments/670949907531563008/780668868971462676/skillapi_Particle_Projectile_bug.mp4) reference

Expected behavior
There should be only one attack.

Desktop (please complete the following information):
 - OS: windows 10
 - Browser: chrome
 - Version: SkillAPI-s1.96

**Comment by Sentropic** [comment]
The area target will pick up all mobs within the area and apply child components to them. What you want is the projectile to damage only the entity it hits? If so, you can remove the area target, and put the damage mechanic directly as a child of the projectile.

**Comment by yhdev7935** [comment]
When deleting AREA, multiple targets cannot be specified.  This problem occurs from Premium and skillapi 3.107 or higher.

**Comment by Sentropic** [comment]
If you do want to target multiple targets, what's the problem in the video?

**Comment by yhdev7935** [comment]
All the skills in the video are the same.
However, damage is added depending on the number of monsters.
Please modify this so there has no additional damage depending on the number of monsters.

**Comment by Sentropic** [comment]
Ohh got it.

**Comment by Sentropic** [comment]
Will be fixed in 1.97!
