### ISSUE TITLE
NoClassDefFoundError: com/sucy/party/Parties

### ISSUE THREAD

**Issue by yhdev7935** [Sentropic/SkillAPI-s#8]
Describe the bug
Unlimited skill bug

To Reproduce
1. [Video](https://cdn.discordapp.com/attachments/587276993624539166/781480194883715112/bug2.mp4) reference

Expected behavior
Skills should not be used indefinitely.

SkillAPI Version: s1.97

**Comment by Sentropic** [comment]
It's caused by an error that gets printed in the console. Next time consider including the console warns in a bug report, since that's more straight forward than replicating a long procedure as that one, that could also result impossible to replicate if the conditions are not the exact same.
